CREATE WAREHOUSE IF NOT EXISTS CHICAGO_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS CHICAGO_RESTAURANT_DB;

CREATE SCHEMA IF NOT EXISTS CHICAGO_RESTAURANT_DB.BRONZE;
