CREATE TABLE IF NOT EXISTS CHICAGO_RESTAURANT_DB.BRONZE.INSPECTIONS_RAW (
    RAW_RECORD VARIANT
);

CREATE TABLE IF NOT EXISTS CHICAGO_RESTAURANT_DB.BRONZE.BUSINESS_LICENSES_RAW (
    RAW_RECORD VARIANT
);
